package com.example.models

import kotlinx.serialization.Serializable

data class HealthTip(
    val title: String,
    val description: String
)

val healthTips = listOf(
    HealthTip("Tip 1", "Stay hydrated"),
    HealthTip("Tip 2", "Get enough sleep"),
    HealthTip("Tip 3", "Eat a balanced diet"),
    HealthTip("Tip 4", "Exercise regularly"),
    HealthTip("Tip 5", "Manage stress")
)
@Serializable
data class Illness( val id: String,
                    val name: String,
                    val summary: String,
                    val headerImageUrl: String?,
                 //   val causes: String,
                 //   val symptoms: String,
                //    val medications: String
                    //val url: String,
                  //  val type: IllnessType,
                    //val causes:List<Causes>
                   // val medications: List<Medication>,)
)

val illnessStorage = listOf(
    Illness("1","Dehydration","Dehydration results when the body loses more liquid than it takes in. This can happen when severe diarrhea, especially when there is vomiting as well. It can also happen in very serious illness, when the person is too sick to take much food or liquid. People of any age can become dehydrated, but dehydration develops more quickly and is most dangerous in small children.Most children who die from diarrhea die because they do not have enough water left in their bodies. Any child with watery diarrhea is in danger of dehydration. Very severe dehydration may cause rapid weak pulse, fast deep breathing, fever or even fits(convulsions)",""),
    Illness("2","Dysentery","When a person has loose or watery stools, they have diarrhea. If mucus and blood can be seen in the stools, they have dysentery",""),
    Illness("3","Headache","Simple headache can be helped by rest and aspirin. It often helps to put a cloth soaked in hot water on the back of the neck and to massage (rub) the neck and shoulders gently. Headache is common with any sickness that causes fever. If the headache is severe check for signs of meningitis. Headaches that keep coming back may be a a sign of chronic illness or poor nutrition. It is important to eat well and get enough sleep. If the headache does not go away, seek medical help. Also see Migraines section.",""),
    Illness("4","Blood Flukes(Schistosomiasis, Bilharzia)","This infection is caused by a kind of worm that gets into the bloodstream. Any person with who have blood in their urine should have their urine checked under a microscope to sse if it has fluke eggs. ",""),
    Illness("5","Vomiting","Many people especially children have an occasional stomach upset with vomiting. Often no cause can be found. THere may be mild stomach or gut ache or fever. This type of simple vomiting is not serious and clears up by itself. Vomiting is one of the signs of many different problems, some minor and some quit serious so it is vital to examine the person carefully",""),
    Illness("6","Stuffy/Running nose","A stuffy or runny nose can result from a cold or allergy. A lot of mucus in the nose may cause ear infection in children or sinus problems in adults",""),
    Illness("7","Sinusitis","Sinusitis is an acute or chronic (long-term) inflammation of the sinuses or hollows in the bone that open into the nose.",""),
    Illness("8","Allergy","An allergy is a disturbance or reaction that affects only certain persons when things are sensitive or allergic to are :- breathed in, eaten, injected, or touch the skin. Allergic reactions which can be mild or very serious include :- itching rashes lumpy patches or hives, runny noe and itching or burning eyes, irritation in the throat, difficulty breathing or asthma, allergic shock , diarrhea(in children allergic to milk- a rare cause of diarrhea). An allergy is not an infection and can not be passed on from one person to another.However children of allergic parents also tend to have allergies.",""),
    Illness("9","Asthma","A person with Asthma has fits or attacks of difficult breathing. Listen for a hissing or wheezing sound especially when breathing out. When breathing in, the skin behind his collar bones and between his ribs may suck in as he tries to get air. If the person can not get enough air, his nails and lips may turn blue and his neck veins may swell. Usually there is no fever. Asthma often begins in childhood and may be a problem for life, It is not contagious but is common in children with relatives who have asthma. It is generally worse during certain months of the year or at night. Persons who have asthma for years may develop emphysema. An Asthma attack may be caused by eating or breathing things to which the persons is allergic to. In children, asthma often starts with common cold. In some persons nervousness or worry also plays a part in bringing on asthma. If you have asthma DO NOT smoke as it damages your lungs even more.",""),
    Illness("10","Cough","Coughing is not a sickness in itself, but a sign of many different sicknesses that affect the throat, lungs or bronchi. Coughing is the bodied way of cleaning the breathing system and getting rid of phlegm. Do not take medicine to stop the cough, rather do something to help loosen and bring up the phlegm.",""),
    Illness("11","Bronchitis","Bronchitis is an infection of the bronchi or tubes that carry air to the lungs. It causes a noisy often with mucus or phlegm. Bronchitis is usually caused by a virus, so antibiotics do not generally help. Use antibiotics only if the the bronchitis lasts more than a week and is not getting better,if the person shows signs of pneumonia of if they already has a chronic lung problem.",""),
    Illness("12","Pneumonia","Pneumonia is an acute infection of the lungs. It often occurs after another respiratory illness such as measles, whooping cough,  flu bronchitis, asthma or any very serious illness.",""),
    Illness("13","Hepatitis","Hepatitis is a virus infection that harms the liver. It causes little or no rise in temperature. It is usually mild in children and more serious in older persons.",""),
    Illness("14","Arthritis(Painful inflamed Joints)","Most chronic joint pain or arthritis in older people can not be cured completely However the following offer some relief :-",""),
    Illness("15","Back pain","Back pain has many causes. Some of which are :-",""),
    Illness("16","Varicose veins","Varicose veins are veins that are swollen, twisted and often painful, often seen on legs of older people and of women who are pregnant or who have had many children.",""),
    Illness("17","Piles(Hemorrhoids)","Piles or hemorrhoids are varicose veins of the anus or rectum which feel like little lumps or balls. They maybe painful but are not dangerous. They frequently appear during pregnancy and may go away afterwards. If a hemorrhoid begins to bleed and does not stop, the bleeding can sometimes be controlled by removing the clot that is inside the swollen vein. Tweezers can be used after they have been sterilized by boiling. Certain bitter plants juices(witch hazel, cactus etc) help shrink them. Piles can be caused in part by constipation. It helps to eat plenty of fruit or fod with a lot of fiber like cassava or bran. Very large hemorrhoids may require an operation. Get medical advice on this.  ",""),
    Illness("18","Swelling of the feet","If this is accompanied by swollen face or other parts of the body then this is usually a sign of serious illness. Women's feet sometimes swell during the last three months of pregnancy. This is usually not serious, it is caused by the weight of the child that presses on the veins coming from the legs in a way that limits the flow of blood. However it the woman's hands and face also swell, she feels dizzy, has problems seeing or does not pass much urine, she may be suffering from poisoning or toxemia of pregnancy.(seek medical help fast). OLd people who spend a lot of time sitting or standing in one place often get swollen feet because of poor circulation. However swollen feet in older persons may also be due to heart trouble or less commonly, kidney disease. Swelling of the feet in small children may result from anemia or malnutrition. In severe cases the face and hands may also become swollen(kwashiorkor)",""),
    Illness("19","Hernia","A hernia is an opening or tear in the muscles covering the belly. This permits a loop of gut to push through and form a lump under the skin. THey usually come from lifting something heavy or straining(as during child birth). Some babies are born with hernia. In men, hernias are common in the groin.",""),
    Illness("20","Fits/Convulsions","We say a person has a fit when he suddenly loses consciousness and makes strange, jerking movements(convulsions). Fits come from a problem in the brain. In small children common causes of fits are high fever and severe dehydration. In very ill persons, the cause may be meningitis, malaria of the brain or poisoning. A person who has fits may have epilepsy",""),
    Illness("21","Tuberculosis","Tuberculosis of the lungs is a chronic (long lasting),it is very contagious(easily spread) disease that any one can get. But it most strikes persons between 15 and 35 years of age- especially those who are weak, are poorly nourished or live with someone who has the disease. Tuberculosis is curable, it is however important to treat it early-Early and full treatment is a key part of prevention.",""),
    Illness("22","Rabies","Rabies come from the bite of a rabid or mad animal, usually a rabid dog,cat,fox,wolf,skunk or jackal. Bats and other animals may also spread rabies.",""),
    Illness("23","Tetanus","Tetanus results when a germ that lives in the feces of animals or people enters the body through a wound. Deep dirty wounds are especially dangerous.",""),
    Illness("24","Meningitis","Meningitis is a very serious infection of the brain, more common in children. It may begin as a complication of another illness such as measles, mumps, whooping cough or an ear infection. Children of mothers who have Tuberculosis sometimes get tubercular meningitis in the first few months of life.",""),
    Illness("25","Malaria","Malaria is an infection o the blood that causes chills and high fever. It is spread by mosquito's .The mosquito sucks up the malaria parasites in the blood of an infected person and injects them into the next person it bites.",""),
    Illness("26","Brucellosis","This is a disease that comes from drinking fresh milk from infected cows or goats. It mat also enter the body through scrapes or wounds in the skin of persons who work with sick cattle, goats or pigs",""),
    Illness("27","Typhoid Fever","Typhoid is an infection of the gut that affects the whole body. It is spread from feces-to-mouth in contaminated food and water and often comes in epidemics(many people sick at once)",""),
    Illness("28","Typhus","Typhus is an illness similar to but different from Typhoid. The infection is transmitted by bites of lice, ticks and rat fleas",""),
    Illness("29","Leprosy(Hansen's disease)","This chronic disease develops very slowly, often over many years. It is not easily spread from one person to another but persons who have lived for a long time in close contact with those who have leprosy sometimes get the disease.",""),

    Illness("30","Gallbladder Problems","",""),
    Illness("31","Cirrhosis of the liver","",""),
    Illness("32","Insomnia","",""),
    Illness("33","Dizziness and Deafness with Ringing of the Ears","",""),
    Illness("34","Stroke","",""),
    Illness("35","Heart Trouble","",""),


    Illness("36","Earache and Ear Infections","",""),
    Illness("37","Sore Throat and Inflamed Tonsils","",""),
    Illness("38","Rheumatic Fever","",""),
    Illness("39","Infectious Diseases of Childhood","",""),
    Illness("40","Chickenpox","",""),
    Illness("41","Measles(Rubeola)","",""),
    Illness("42","German Measles(Rubella)","",""),
    Illness("43","Mumps","",""),
    Illness("44","Whooping Cough","",""),
    Illness("45","Diphtheria","",""),
    Illness("46","Infantile Paralysis(Polio)","",""),
    Illness("47","Dislocated Hip","",""),
    Illness("48","Umbilical Hernia","",""),
    Illness("49","A' Swollen Testicle'(Hydrocele or Hernia)","",""),
    Illness("50","Mentally Slow,Deaf or Deformed Children","",""),
    Illness("51","The Spatic Child(Cerebral Palsy)","",""),
    Illness("52","Retardation in the first months of life","",""),
    Illness("53","Helping Children Learn","",""),

    Illness("54","Infertility","Either the man or the woman may be infertile(unable to bring about pregnancy). Often nothing can be made to make the person fertile, but sometimes something can be done depending on the cause. Some causes include but not limited to:- Sterility, Weakness or a nutritional lack and Chronic infection. Men are sometimes unable to make their women pregnant because they have fewer sperms than is normal. It may help for the man to wait without having sex for several days before his woman enters her fertile days each month midway midway between her last menstrual period and the next. THis will help give her his full amount of sperm when they have sex together on days when she is able to become pregnant.. Hormones and other medicines commonly given to men or women who cannot have babies are not likely to help.",""),
    Illness("55","Pain and discomfort in a woman's belly","",""),
    Illness("56","Vaginal Discharge","A mucus or pus-like stuff that comes from the vagina. All women normally have a small amount of vaginal discharge, which is clear, milky or slightly yellow. If there is no itching or bad smell, there is probably no problem. But many women, especially during pregnancy suffer from a discharge often with itching in the vagina. THis discharge may be caused by various infections. A thin and foamy greenish-yellow or whitish foul smelling discharge with itching. This is probably an infection or Trichomonas. It burns to urinate. Sometimes the genitals hurt or are swollen. If white discharge that looks like cottage cheese or buttermilk, and smell like mold, mildew or baking bread, this could be a yeast infection. itching may be severe. The lips of the vagina often look bright and red and hurt. It burns to urinate. THe thrush is especially common in pregnant women or in those who are sick, diabetic or have been taking antibiotics or birth control pills.",""),
    Illness("57","Bubos:Bursting Lymph Nodes in the Groin","In a man: Large dark lumps in the groin that open to drain pus, scar up and open again. In a woman: Lymph nodes similar to those in the man. Or painful oozing sores in the anus. ",""),
    Illness("58","Syphilis","Syphilis is a common and dangerous disease that is spread from person to person through sexual contact. Without adequate treatment, syphilis can invade any part of the body causing heart disease, paralysis, insanity and many other problems. If any strange rash or skin condition shows up days or weeks after a pimple or sore appears on the genitals, it may syphilis. If unsure, get medical advice.",""),
    Illness("59","Gonorrhea(Clap, VD, the Drip)","This is a disease usually spread by sexual contact(a venereal disease). In a man, the first signs of gonorrhea begin 2 to 5 days(or up to 3 weeks or more ) after sexual contact with an infected person. In a woman, years pass before any signs show up. But even though she does not show any signs, she can give the disease to someone else starting a few days after she becomes infected.",""),
    Illness("60","Enlarged Prostate Gland","This condition is most common in older men. It is called by a swelling of the prostate gland, which is between the bladder and the urinary tube(urethra). The person has difficulty in passing urine and sometimes in having a bowel movement. The urine may only dribble or drip or become blocked completely. Sometimes the man is not able to urinate for days. If he has a fever, this is a sign that infection is also present.",""),

    Illness("61","Kidney or Bladder Stones","",""),
    Illness("62","Urinary Tract Infections","",""),
    Illness("63","White Patches or Spots in the Mouth","",""),
    Illness("64","Sores or Cracks at the corners of the mouth","",""),
    Illness("65","Pyorrhea","",""),
    Illness("66","Toothaches and Abscesses","",""),

    Illness("67","Menstrual Period Problems","Most girls have their first periods or monthly bleeding between the ages of 11 and 16. This means that they are now old enough to become pregnant.. The normal period comes once every 28 days or so, and lasts 3 to 6 days. However this varies a lot in different women. Irregular or painful periods are common in adolescent (teenage) girls. This does not usually mean there is anything wrong. If your menstrual period is painful, There is no need for you to stay in bed. In fact lying quietly can make the pain worse. It often helps to walk around and do light work or exercise or take hot drinks or put your feet in hot water. It may also help to put hot compresses on the belly. Some irregularity in the length of time between periods is normal for certain women, but for others it may be a sign of chronic illness, anemia, malnutrition or possibly an infection or tumor in the womb. If the period does not come when expected could be a sign of pregnancy. If bleeding starts during pregnancy it is almost the beginning of a miscarriage. If the menstrual period lasts more than 6 days, results in heavy bleeding or comes more than once a month seek medical advice. ",""),
    Illness("68","Menopause","THe menopause or climacteric is the time in a woman's life when the menstrual period stops coming. After menopause she can no longer bear children normally between the ages of 40 and 50. The periods often become irregular for several months before they stop completely. During menopause, it is normal for a woman to feel many discomforts- anxiety, distress, hot flashes, pains that travel all over the body, sadness etc After menopause is over many women feel better again. ",""),
    Illness("130","Difficult Births","",""),
    Illness("131","Care of the newborn baby","",""),
    Illness("132","Illnesses of the newborn","",""),
    Illness("133","Care of the breasts","",""),
    Illness("134","Lumps or Growths in the lower part of the belly","",""),
    Illness("135","Miscarriage","",""),
    Illness("136","Family Planning","",""),
    Illness("69","Pregnancy","Signs of pregnancy. All these signs are normal. THe woman misses her period(often the first sign), Morning sickness(nausea or feeling you are going to vomit especially in the morning.) This is worse during the second and third months of pregnancy. She may have to urinate more often. The belly gets bigger, The breasts get bigger. Mask of pregnancy(dark areas on the face, breasts and belly), Finally ,during the fifth month or so the child begins to move in the womb. To stay health during pregnancy the body needs food rich in proteins, vitamins and minerals especially iro so it is important to eat well. USe iodized salt to increase the chances that the child will be born alive and not be retarded(But to avoid swelling of the feet and other problems, do not use very much salt.), Keep clean-Bathe or wash regularly and brush your teeth every day. It is perhaps best to avoid sexual contact in the last month to keep from breaking the bag of waters and causing an infection. Avoid taking medicines. Only take medicines recommended by a health worker. Do not smoke or drink during pregnancy. Stay away from children with measles especially German measles. Continue to work and get exercise but try not to get too tired.  Minor problems during pregnancy: Nausea or vomiting- it helps to eat something drybefore you get out of bed in the morning Do not eat large meals rather smaller amounts of food several times a day and avoid greasy foods. Burning or pain-if possible drink milk avoid taking antacids, it helps to suck hard candy and try to sleep with the chest and head lifted up some wit pillows or blankets. Swelling of the feetREst at different times during the day with your feet up. Eat less salt and avoid salty foods, Tea made from corn silk may help. If the feet are very swollen and the hands and face also swell, seek medical advice.Low back pain- it can be helped by exercise and taking care to stand and sit with the back straight. Anemia and malnutrition- eat more protein(beans,groundnuts,chicken,milk,cheese,eggs,meat,fish and dark green leafy vegetables. Swollen veins(varicose veins)-Put your feet up often as high as you can. If the veins get very big or hurt wrap them with an elastic bandage take off the bandages at night. Piles(hemorrhoids) -These are varicose veins in the anus they result from the weight of the baby in the womb. To relieve the pain, kneel with the buttocks in the air. Constipation: Drink plenty of water. Eat fruits and food with a lot of fibre like cassava or bran. Get plenty of exercise and do not takes strong laxatives.)",""),


    Illness("74","Roundworm(Ascaris)","",""),
    Illness("75","Whip-worm","",""),
    Illness("76","Hookworm","",""),
    Illness("77","Tapeworm","",""),
    Illness("78","Trichinosis","",""),
    Illness("79","Amebas","",""),
    Illness("80","Giardia","",""),
    Illness("70","Birth Control","",""),
    Illness("71","Preparing for birth","",""),
    Illness("72","Signs and Stages if labour","",""),
    Illness("73","Care of the baby at birth","",""),

    Illness("81","Migraine","Is a severe and throbbing headache often on one side of the head only. It may come often or months or years apart. A typical migraine begins with a blurring of vision, seeing strange spots of light or numbness of one hand or foot. This is followed by severe headache, which may last hours or days. Often there is vomiting. Migraines are very painful but not dangerous",""),
    Illness("82","Cold and Flu","Colds and flu are common virus infections that mas cause runny nose, cough, sore throat and sometimes fever or pain in the joints. There may be mild diarrhea especially in young children. Cold/Flu almost go away without any medication. Do not use antibiotics as they will not help all and may cause harm. Drink plenty of water and get enough rest. Aspirin helps lower the fever and relieve body aches and headaches. More expensive cold tablets are no better than aspirin, so why waste your money. No special diet is needed. However fruit juices especially orange juice or lemonade are helpful. If a cold or the flu lasts more than a week, or if the person has fever, coughs up a lot of phlegm(mucus with pus), has shallow fast breathing or chest pain, they could be developing bronchitis or pneumonia and antibiotics may be called for. The danger of a cold turning into pneumonia is greater in old people and those who have lung problems like chronic bronchitis. Sore throat is often part of a cold. No special medicine is needed, but it may help to gargle with warm water. However if the soar throat begins suddenly with high fever, it could be a strep throat. Special treatment is needed.",""),
    Illness("83","Hay Fever(Allergic Rhinitis)","Running nose and itchy eyes can be caused by an allergic reaction to something in the air that a person has breathed in. It is often worse at certain times of the year",""),
    Illness("84","Epilepsy","Epilepsy causes fits in people who otherwise seem fairly healthy. It may come hours, days,weeks or months apart. In some persons it causes loss of consciousness and violent movements, the eyes often roll back. In mild types of epilepsy, the person may suddenly blank out a moment, make strange movements or behave oddly. Epilepsy is more common in some families(inherited), or it may come from brain damage at birth, high fever in infancy or tapeworm cysts in the brain. It is not an infection and can not be caught. it is often a long-life problem, however infants sometimes get over it.",""),
    Illness("85","Scabies","Scabies is especially common in children. It causes very itchy little bumps that can appear all over the body but are most common between the fingers,on the wrists, around the waist and or on the genitals. They are caused by little animals-similar to tiny ticks or chiggers- which make tunnels under the skin. It is spread by touching the affected skin or by clothes and bedding.. Scratching can cause an infection producing sores with pus and sometimes swollen lymph nodes or fever.",""),
    Illness("86","Small sores with pus","Skin infections in the form of small sores with pus often result from scratching insect bites, scabies or other irritations with dirty fingernails.",""),
    Illness("87","Impetigo","This is a bacterial infection that causes rapidly spreading sores with shiny, yellow crusts. It often occurs on children's faces especially around the mouth. It can easily spread to other people from the sores of contaminated finger.s.",""),
    Illness("88","Boils And Abscesses","A boil or abscess is an infection that forms a sac of pus under the skin. Sometimes it results from a puncture wound or an injection given with a dirty needle. A boil is painful and the skin around it becomes red and hot. It can cause swollen lymph nodes and fever.",""),
    Illness("89","Itching Rash, Welts or Hives(Allergic reactions in the skin)","Touching, eating or breathing certain things can cause an itching rash or hives in allergic persons. Hives are thick, raised spots or patches that look like bee stings and itch like mad. They may come and go rapidly or move from one one spot to another.",""),
    Illness("90","Ringworm(Fungus infection)","Fungus infection may appear on any part of the body, but occur most frequently on the scalp(Tinea), the parts without hair(ringworm),between the toes or fingers(athlete's foot) and or between the legs(jock itch). MOst fungus infection grow in the form of a ring, and they often itch. Ringworm of the head can produce round spots with scales and loss of hair. Fingernails infected with the fungus become rough and thick.",""),
    Illness("91","White spots on the face and body","Small dark or light spots with distinct and irregular border that are often seen on the back neck, chest and back me be fungal infection called tinea versicolor. It usually does not itch and is of little medical importance.",""),
    Illness("92","Mask of pregnancy","During pregnancy many women develop dark olive-colored areas on the skin of the face, breasts and down the middle of the belly. Sometimes they disappear after child birth and sometimes not. These marks also appear sometimes on women who are taking birth control pills.They are completely normal and do not indicate weakness or sickness. No treatment is needed. ",""),
    Illness("93","Pellagra","Pellagra is a form of malnutrition that affects the skin and sometimes the digestive system and nervous systems. It si very common in places where people eat a lot of maize(corn) or other starchy foods and not enough beans, meat,eggs,vegetables and other body building and protective foods.",""),
    Illness("94","Warts","Most warts, especially those in children last 3  to 5 years and go away by themselves. Flat and painful wart-like spots on the sole of the foot are often planter warts or they may be corns",""),
    Illness("95","Corns","A corn is a hard, thick part of the skin. It forms where sandals or shoes push against the skin or one toe presses against another. Corns can be very painful",""),
    Illness("96","Pimples And Blackheads(Acne)","Young people sometimes get pimples on their face, chest or back especially if their skin has too much oil in it",""),
    Illness("97","Tuberculosis of the skin or Lymph nodes","The same microbe that causes tuberculosis of the lungs also sometimes affects the skin. As a rule of thumb, TB of the skin develops slowly, lasts a long time and keeps coming back over a period of months or years.",""),
    Illness("98","Erysipelas","This is a very painful, acute infection in the skin. It forms a hot red, swollen patch with a sharp border. THe patch spreads rapidly over the skin. It often begins on the face at the edge of the nose. THis usually causes swollen lymph nodes, fever and chills ",""),
    Illness("99","Gangrene","This is a very dangerous infection of a wound in which a foul-smelling gray or brown liquid forms. THe skin near the wound may have dark blisters and the flesh may have air bubbles in it. The infection begins between 6 hours and 3 days after the injury. It quickly gets worse and spreads fast. Without treatment it causes death in  few days.",""),
    Illness("100","Bed Sores","These chronic open sores appear in persons so ill they cannot roll over in bed, especially in sick old persons who are very thin and weak. THe sores form over bony parts of the body where the skin is pressed against the bedding. THey are most often seen on the buttocks, back, elbows or feet.",""),
    Illness("101","Diaper Rash","Reddish patches of irritation between a baby's legs or buttocks. May be caused by urine in his diapers(nappy) or bedding",""),
    Illness("102","Cradle Cap","Cradle cap is an oily, yellow crust that forms on a baby's scalp. The skin is often red and irritated. Cradle cap usually results from not washing the baby's head often enough, or from keeping the head covered.",""),
    Illness("103","Eczema(Red patches with little blisters)","In small children: a red patch or rash forms on the cheeks or sometimes on the arms and hands. THe rash consists of small sores or blisters that ooze or weep(burst and leak fluid). In Older children and grown-ups:Eczema is usually drier and is most common behind the knees and on the inside of the elbows. It does not start as an infection but is more like an allergic reaction.",""),
    Illness("104","Psoriasis","Thick, rough patches of reddish or blue-gray skin covered with whitish or silver-colored scales. The condition usually lasts a long time or keeps coming back. It is not an infection and is not dangerous.",""),
    Illness("105","Injuries to the Eye","All injuries to the eyeball must be considered dangerous, for they may cause blindness. Even small cuts on the cornea(the  transparent layer covering the pupil and iris) may get infected and harm the vision if not cared for correctly. If a wound to the eyeball is so deep it reaches the black layer beneath the outer whiter layer, this is especially dangerous.If a blunt injury(as with a fist) causes the eyeball to fill with blood, the eye is in danger especially if pain suddenly gets much worse after a few days, for this is probably acute glaucoma",""),
    Illness("106","Red painful eyes- Different causes","Foreign matter,burn or harmful liquids, pink eye(conjunctivitis), hay fever(allergic conjunctivitis),trachoma,measles,acute glaucoma,iritis,scratch or ulcer on the cornea",""),
    Illness("107","Pink Eye(Conjunctivitis)","This infection causes redness, pus and mild burning in one or both eyes. Lids often stick together after sleep",""),
    Illness("108","Trachoma","Trachoma is a chronic form of conjunctivitis that slowly gets worse. It may last for months or many years. If not treated early, it sometimes causes blindness. It is spread by touch or by flies and is most common where people live in poor crowded conditions.",""),
    Illness("109","Neonatal Conjunctivitis(Infected eyes in newborn babies)","In the first 2 days of life, if a newborn baby's eyes get red, swell and have a lot of pus in them, this is probably from their mother at birth. It must be treated at once to prevent the baby from going blind. ",""),
    Illness("110","Iritis(Inflammation of the Iris)","Pain may begin suddenly or gradually. The eye waters a lot. It hurts more in bright light. There is no pus as with conjunctivitis and vision is usually blurred. This is a medical EMERGENCY. Antibiotic ointments do not help. Get medical help.",""),
    Illness("111","Glaucoma","This dangerous disease is the result of too much pressure in the eye. It usually begins after the age of 40 and is common cause of blindness. To prevent blindness, it is important to recognize the signs of glaucoma and get medical help fast. With Acute glaucoma, is starts suddenly with a headache or severe pain in the eye. THe eye becomes red, the vision blurred, the eyeball feels hard to the touch like a marble. There may be vomiting. THe pupil of the bad eye is bigger than that of the good eye. Surgery is often needed sooner than later. With Chronic glaucoma, the pressure in the eye rises slowly. Usually there is no pain. Vision is lost slowly starting from the side and often the person does not notice the loss. Testing the side vision may help detect the disease.If discovered early, treatment with special eye drops may help  ",""),
    Illness("112","Dacryocystitis( Infection of the tear sac)","Redness, pain and swelling beneath the eye next to the nose. The eye waters a lot. A drop of pus may appear in the corner of the eye when the swelling is gently pressed.",""),
    Illness("113","Cross Eyes and wandering Eyes","If a baby or young child has one eye that turns in(cross-eye) or out(wall-eye) or that sometimes look the wrong way(wanders) try covering the good eye with a patch. If possible do this when the child is 6 months old. Keep the good eye covered until the other eyes stays straight. For a 6-month-old baby this may only take a week or two. Older children take longer up to a year fora 7-year old. If one eye is turned the wrong way, it is less likely that covering the good eye will help. Special glasses sometimes help .The eyes can perhaps be straightened by surgery, but this does not usually help the person see better.",""),
    Illness("114","STY(Hordeolum)","A red, swollen lump on the eyelid usually near its edge. To treat apply warm moist compresses with little salt in the water. Use of an antibiotic eye ointment 3 times a day will help prevent more sties from occurring ",""),
    Illness("115","Pterygium","A fleshy thickening on the eye surface that slowly grows out from the edge of the eye and onto the cornea, caused in part by sunlight, wind and dust. Dark glasses may help calm irritation and slow the growth of a pterygium. It should be removed by surgery before it reaches the pupil. Eye drops of camomile tea(well boiled and without sugar) may help calm itching and burning ",""),
    Illness("116","Bleeding the white of the eye","A painless blood-red patch in the white part of the eye occasionally appears after lifting something heavy, coughing had(as with whooping cough) or being hit on the eye. The condition results from the bursting of a small blood vessel. It is harmless and will slowly disappear without treatment. Small red patches are common on the eyes of newborn babies. No treatment is needed ",""),
    Illness("117","Hyphema(Bleeding behind the cornea)","Blood behind the cornea is a dangerous sign. Usually results from an injury to the eye with a blunt object like a fist. Treat it by patching the eyes and keeping the person at rest in bed for several days. If after a few days tha pain becomes much worse, there is probably hardening of the eye(glaucoma). Take the person to an eye doctor at once.",""),
    Illness("118","Hypopyon(Pus behind the cornea)","Pus behind the cornea is a sign of severe inflammation. It is sometimes seen with corneal ulcers and is a sign that the eye is in danger. If treated correctly, it will often clear up by itself.",""),
    Illness("119","Cataract","THe lens of the eye behind the pupil becomes cloudy, making the pupil look gray or white when you shine a light into it. It is common in older persons but also occurs rarely in babies. If a blind person with cataracts can still tell light from dark and notice motion, surgery may let him see again. However he will need strong glasses afterward which takes time to get used to. Medicines do not help cataracts.",""),
    Illness("120","Night Blindness and Xerosis(Vitamin A deficiency)","This eye disease is most common in children between 2 and 5 years of age. It comes from not eating enough foods with vitamin A. if not recognized and treated early, it can make the child blind.",""),
    Illness("121","Spots or flies before the eyes(Mouches Volantes)","Sometimes older persons complain of small moving spots when they look at a bright surface(wall, sky). The spots move when the eyes move and look like tiny flies. They are usually harmless and need no treatment. However if they appear suddenly in large numbers and vision begins to fail from one side, this could be a medical emergency(detached retina). Medical help is needed at once.",""),
    Illness("122","Double Vision","Seeing double can have many causes.If if comes suddenly, is chronic or gradually gets worse, it is probably a sign of serious problem. Seek medical help. If it occurs only from time to time, it may be a sign of weakness or exhaustion perhaps from malnutrition.",""),
    Illness("123","River Blindness(Onchocerciasis)","The infection is caused by tiny worms that are carried from person to person by small, hump-backed flies or gnats known as black flies(simulids). THe worms are injected into a person when the infected black fly bites them.",""),
    Illness("124","Toothaches and abscesses","A toothache results when a cavity becomes infected. An abscess results when the infection reaches the tip of a root and forms a pocket of pus.To calm the pain:- clean the hole in the tooth wall, removing all food particles. then rinse the mouth with warm salt water. If the tooth infection is severe(swelling pus, large tender lymph nodes), use an antibiotic. iF the pain does not go away or keeps coming back, the tooth should probably be pulled. Treat abscesses right away- before the infection spreads to other parts of the body.",""),
    Illness("125","Pyorrhea(A disease of the gums)","Inflamed(red and swollen)painful gums that bleed easily caused by not cleaning the teeth and gums well or often enough. or by not eating enough nutritious foods. Note: Sometimes medicines for fits(epilepsy) cause swelling and unhealthy growth of the gums, in which case consult a health worker and consider using a different medicine. ",""),
    Illness("126","Sores or Crack at the corners of the mouth","Narrow sores at the corners of children's mouth are often a sign of malnutrition. Children with these sores should eat foods rich in vitamins and proteins like milk, meat, fish, nuts, eggs, fruits and green vegetables. ",""),
    Illness("127","White patches or spots in the mouth","The tongue is coated with white fur. Many illnesses cause a white or yellowish coating on the  tongue and roof of the mouth. This is common when there is a fever. Although this coating is not serious, it help to rinse the mouth with a solution of warm water with salt and bicarbonate of soda several times a day. Tiny white spots like salt grains in the mouth of a child with fever may be an early sign of measles.  Thrush: Small white patches on the inside of the mouth and tongue that look like milk curds stuck to raw meat. THey are caused by a fungus or yeast infection called moniliasis. It is common in newborn babies and in persons using certain antibiotics. Unless it is very necessary to keep taking the antibiotic, stop taking it. Paint the inside of the mouth with gentian violet. Chewing garlic or eating yoghurt may also help. Canker Sores:-small, white, painful spots inside the lip or mouth. MAy appear after fever or stress(worry). Goes away in 1 to 3 weeks. Rinse the mouth with salty water or put little hydrogen peroxide or cortico-steroid ointment. Antibiotics do no help.",""),
    Illness("128","Cold Sores And Fever Blister","Small painful blisters on lips(or genitals) that break and form scabs. May appear after fever or stress. Caused by herpes virus. THey heal after 1 or 2 weeks. Holding ice on the sores for 1 hour the day they begin may cure them. No medications do much good.",""),


    Illness("129","Glaucoma","",""),




    )


//How to  remove a speck of dirt from the eye